joint0:
  serial_port: /dev/ttyACM0
  baud_rate: 921600
  can_id: 1
  mst_id: 17
  motor_type: DM4340

joint1:
  serial_port: /dev/ttyACM1
  baud_rate: 921600
  can_id: 3
  mst_id: 19
  motor_type: DM4340